export const ALL_PRODUCTS_REQUEST="ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS="ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAILED="ALL_PRODUCTS_FAILED"

export const CLEAR_ERRORS="CLEAR_ERRORS"