export const ALL_PRODUCTS_REQUEST="ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS="ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAILED="ALL_PRODUCTS_FAILED"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAILED="PRODUCT_DETAILS_FAILED"

export const CLEAR_ERRORS="CLEAR_ERRORS"